import type { BookMeta } from "@/lib/types";

export const meta: BookMeta = {
  slug: "kimi",
  title: "Kimi · 从长文本到一套 agent 栈",
  titleEn: "",
  coverTitle: "从长文本到一套 agent 栈",
  subtitle:
    "K3 旗舰（2.8 万亿参数、1M 上下文、思考永远开）与 K2.7-Code 编码专线, 撑起一套整合的 agent 栈: 四模式、做出网站幻灯文档表格的 Agent、最多 300 子 agent 的 Swarm、Deep Research、跑在终端的 Kimi Code、常驻的 Kimi Claw、五档会员, 底下是 OpenAI + Anthropic 双兼容、K2 系开源权重的 API。国内可达、中文长材料顺手。哪一面该用、买哪档够用、什么时候回 frontier。",
  description:
    "很多人对 Kimi 的印象还停在「长文本」那一年 —— 一次吃几万字、中文写得稳。那是它的旧定位。它现在给自己的定位是「为智能体编程与知识工作打造」: 一套整合的 agent 栈 —— K3 旗舰（2.8 万亿参数、1M 上下文、思考永远开）与 K2.7-Code 编码专线, 四种模式、做出成品的 Agent、最多 300 子 agent 的 Swarm、Deep Research、跑在终端的 Kimi Code、常驻的 Kimi Claw, 五档会员, 再加一套 OpenAI / Anthropic 双兼容、K2 系开源权重打底的 API。它早已不靠便宜取胜 —— K3 直接把价格定在了 frontier 那一栏; 最难的活, 官方自己也承认还差 Claude Fable 5 / GPT 5.6 Sol 半步。这本书给这套栈画张图: 每块产品干什么、对标前沿的哪一个、买哪档够用、什么活该交给它、什么时候回 frontier, 厂商自评与独立实测分开算账。截至 2026-07。",
  descriptionEn: "",
  // Card copy — short forms shown on home / library cards.
  titleShort: "Kimi",
  lede: "别再把它当长文本工具 —— K3 旗舰思考永远开, 一套整合的 agent 栈加双兼容 API, 国内可达、中文长材料顺手; 该用的那几面替你挑出来, 什么时候回 frontier 也说清。",
  cover: "/books/kimi/cover.jpg",
  author: "Zhaphar",
  date: "2026-07-17",
  language: "zh",
  draft: false,
  tags: ["TECH", "PRACTICE"],
  category: "TECH",
  readMinutes: 69,
  chapters: [
    {
      slug: "01-intro",
      title: "引子 · 我印象里的 Kimi 是旧的",
      titleShort: "引子",
      titleEn: "",
      readTime: "5 MIN",
      publishedAt: "2026-06-12",
      revisions: [{ v: 1, date: "2026-06" }, { v: 2, date: "2026-07" }, { v: 3, date: "2026-07" }],
      lede: "我对 Kimi 的印象, 曾停在「长文本」那一年 —— 付了费, 却只用它读长文、写中文。到 K3 回头一看, 它早长成一套对标 OpenAI / Anthropic 的全栈。这本书, 是我把这套栈一块块拆开看的记录。",
      posterSummary: "两年时间, 它从「能读长文的框」长成模型、Agent、API 一整套栈。印象不更新, 就只用到它的一个角。",
    },
    {
      slug: "02-stack",
      title: "全景 · 一套对标前沿的栈",
      titleShort: "全景",
      titleEn: "",
      readTime: "7 MIN",
      publishedAt: "2026-06-12",
      revisions: [{ v: 1, date: "2026-06" }, { v: 2, date: "2026-07" }],
      lede: "我把 Kimi 的产品线整个摆开, 才发现自己天天用的只是那个聊天框 —— 背后是五件套: 网页本体、Kimi Work、Kimi Code、WebBridge、开放平台 API, 几乎能跟 OpenAI 和 Anthropic 一一对上号。这章不教任何一面怎么用, 只给整套栈画张图: 哪一面对着哪类活、对标谁、哪两条账别混。",
      posterSummary: "把 Kimi 的入口和 ChatGPT、Claude 一一对上号, 它早长成一套完整的栈。这张图不画出来, 用上的就永远只有天天开的那个框。",
    },
    {
      slug: "03-models",
      title: "挑模型 · K3、K2.7-Code 与 K2.6",
      titleShort: "挑模型",
      titleEn: "",
      readTime: "7 MIN",
      publishedAt: "2026-06-12",
      revisions: [{ v: 1, date: "2026-06" }, { v: 2, date: "2026-07" }],
      lede: "输入框那个模型名, 我自己也很久没换过 —— 直到 K3 来了: 2.8 万亿参数、1M 上下文, 思考再也关不掉。这章我把三颗在列的脑子摆上解剖台, 四件典型活一笔一笔算账: 哪件配哪颗、为什么、大概多少钱。",
      posterSummary: "三颗模型的分别在上下文、思考开关和单价。账不算, 就为用不上的旗舰推理付了钱。",
    },
    {
      slug: "04-modes",
      title: "四模式 · 快答、深想、交办、集群",
      titleShort: "四模式",
      titleEn: "",
      readTime: "6 MIN",
      publishedAt: "2026-06-12",
      revisions: [{ v: 1, date: "2026-06" }, { v: 2, date: "2026-07" }],
      lede: "输入框旁边的模式开关, 我自己长期没动过 —— Instant / Thinking / Agent / Agent Swarm, 是 Kimi 把「答你一句」和「替你做成」分开的旋钮。挑错了, 要么干等, 要么不够使。这章我给一张对照加四个场景, 和一条贯穿始终的判断。",
      posterSummary: "同一个输入框, 四档模式干的是四种活: 前两档「它答、你做」, 后两档「它做、你验」。判断只有一条 —— 挑能办成事的最低那一档, 更高的档不等于更好的结果。",
    },
    {
      slug: "05-agent",
      title: "交办 · Agent 直接做成品",
      titleShort: "交办",
      titleEn: "",
      readTime: "7 MIN",
      publishedAt: "2026-06-12",
      revisions: [{ v: 1, date: "2026-06" }, { v: 2, date: "2026-07" }],
      lede: "网页对话里它答我; Agent 模式里它替我做 —— 我说清要什么, 它交回网站、幻灯、文档、表格。这一章是我交办用下来的账: 什么时候该把整件活交给它、一次交办的真实成本是多少, 什么时候它只是把活做快、做砸。",
      posterSummary: "Agent 交的是排好版的 PPT、算好的表、能上线的网页; 一次交办 5–20 分钟、吃共享额度、128K 上下文。验收标准写在它出发前, 它做得成; 说不清, 它只会快快地做错。",
    },
    {
      slug: "06-swarm",
      title: "大活 · Agent Swarm 与 Kimi Claw",
      titleShort: "大活",
      titleEn: "",
      readTime: "7 MIN",
      publishedAt: "2026-06-12",
      revisions: [{ v: 1, date: "2026-06" }, { v: 2, date: "2026-07" }],
      lede: "我手里有一类活, 单件都不难, 难在一个「多」字。Agent Swarm 用规模换时间, 一次放一群子 agent 并行; Kimi Claw 用自主换托管, 一个常驻 agent 7×24 替你动手。这一章我拆这两条线的账: 什么活值得动用, 动用之前要先认清什么代价。",
      posterSummary: "一群子 agent 并行换时间, 一个常驻 agent 用自主换托管。阵仗越大, 要先认清的代价越具体。",
    },
    {
      slug: "07-research",
      title: "查证 · Deep Research 出带出处的报告",
      titleShort: "查证",
      titleEn: "",
      readTime: "7 MIN",
      publishedAt: "2026-06-12",
      revisions: [{ v: 1, date: "2026-06" }, { v: 2, date: "2026-07" }],
      lede: "有些问题, 一段聊天回答不够用 —— 我要的是一份能拿去用、每条结论都带出处的报告。这一章, 是我给 Kimi 深度研究划的那条线: 什么活值得等这一趟, 什么活普通对话三秒就够。",
      posterSummary: "深度研究把「自己开 20 个标签页」的那一下午, 换成一趟 10–25 分钟的等待和一份每条结论带出处的报告。值得等的是要拿结论做决定的多来源调研; 查个事实, 普通对话三秒就够。",
    },
    {
      slug: "08-code",
      title: "写码 & 接 API · 把 Kimi 配进你的 Agent",
      titleShort: "写码",
      titleEn: "",
      readTime: "12 MIN",
      publishedAt: "2026-06-12",
      revisions: [{ v: 1, date: "2026-06" }, { v: 2, date: "2026-07" }],
      lede: "Kimi Code 是跑在终端、对标 Claude Code 的第一方编码 agent; 开放平台有 OpenAI 与 Anthropic 两套兼容协议, Claude Code、OpenCode、Pi 改几行配置就能接, Codex 要借 CC-Switch 的本地路由。这章我给每个 agent 摆出最小配置, 哪里接不了也明说。",
      posterSummary: "终端里的 Kimi Code、OpenAI / Anthropic 双兼容的 API、一键切换的 CC-Switch, 是国内开发者顺手的三件套。Kimi 一侧有三套账户、两套协议, 配错哪一处, 报的都是同一个 401。",
    },
    {
      slug: "09-selection",
      title: "选档 & 取舍 · 买哪档, 什么时候回 frontier",
      titleShort: "选档",
      titleEn: "",
      readTime: "6 MIN",
      publishedAt: "2026-06-12",
      revisions: [{ v: 1, date: "2026-06" }, { v: 2, date: "2026-07" }],
      lede: "我挑档不盯价格, 盯的是我缺 Agent 次数、Agent 集群, 还是 Kimi Code 额度。这章我把五档会员摆开, 附上我自己 Allegretto 档一个月的 token 实测, 说清订阅不含 API 这条线, 也算清什么活回 Claude / GPT、什么活交给 DeepSeek。",
      posterSummary: "五档会员差的是分项额度, 不是模型; 订阅也不含 API。买对那一档、把对不上的活交出去, 比追更高的档位重要。",
    },
    {
      slug: "10-playbook",
      title: "实战速查 · 哪类活该用哪一面",
      titleShort: "速查",
      titleEn: "",
      readTime: "5 MIN",
      publishedAt: "2026-06-12",
      revisions: [{ v: 1, date: "2026-06" }, { v: 2, date: "2026-07" }],
      isLastChapter: true,
      lede: "前面九章, 我把这套栈的每一面单独拆开算过账。这一章把判断压成一页速查: 哪类活走哪一面、怎么用、别怎么用。对上哪一行, 就走那一面; 对不上, 别硬留在它这。",
      posterSummary: "一套栈十几面, 最常见的浪费是拿错了面: 拿 Agent 问事实, 拿旗舰跑批量。对上哪一行就走哪一面, 对不上的活, 交给别人。",
    },
  ],
};
