import type { BookMeta } from "@/lib/types";

export const meta: BookMeta = {
  slug: "kimi",
  title: "Kimi · 从长文本到一套 agent 栈",
  titleEn: "",
  coverTitle: "从长文本到一套 agent 栈",
  subtitle:
    "K3 旗舰（2.8 万亿参数、1M 上下文、思考永远开）与 K2.7-Code 编码专线, 撑起一套整合的 agent 栈: 四模式、做出网站幻灯文档表格的 Agent、最多 300 子 agent 的 Swarm、Deep Research、跑在终端的 Kimi Code、常驻的 Kimi Claw、五档会员, 底下是 OpenAI + Anthropic 双兼容、K2 系开源权重的 API。国内可达、中文长材料顺手。哪一面该用、买哪档够用、什么时候回 frontier。",
  description:
    "很多人对 Kimi 的印象还停在「长文本」那一年 —— 一次吃几万字、中文写得稳。那是它的旧定位。它现在给自己的定位是「为智能体编程与知识工作打造」: 一套整合的 agent 栈 —— K3 旗舰（2.8 万亿参数、1M 上下文、思考永远开）与 K2.7-Code 编码专线, 四种模式、做出成品的 Agent、最多 300 子 agent 的 Swarm、Deep Research、跑在终端的 Kimi Code、常驻的 Kimi Claw, 五档会员, 再加一套 OpenAI / Anthropic 双兼容、K2 系开源权重打底的 API。它早已不靠便宜取胜 —— K3 直接把价格定在了 frontier 那一栏; 最难的活, 官方自己也承认还差 Claude Fable 5 / GPT 5.6 Sol 半步。这本书给这套栈画张图: 每块产品干什么、对标前沿的哪一个、买哪档够用、什么活该交给它、什么时候回 frontier, 厂商自评与独立实测分开算账。截至 2026-07。",
  descriptionEn: "",
  // Card copy — short forms shown on home / library cards.
  titleShort: "Kimi",
  lede: "别再把它当长文本工具 —— K3 旗舰思考永远开, 一套整合的 agent 栈加双兼容 API, 国内可达、中文长材料顺手; 该用的那几面替你挑出来, 什么时候回 frontier 也说清。",
  cover: "/books/kimi/cover.jpg",
  author: "Zhapar",
  date: "2026-07-17",
  language: "zh",
  draft: false,
  tags: ["TECH", "PRACTICE"],
  category: "TECH",
  readMinutes: 69,
  chapters: [
    {
      slug: "01-intro",
      title: "引子 · 你印象里的 Kimi 是旧的",
      titleShort: "引子",
      titleEn: "",
      readTime: "5 MIN",
      publishedAt: "2026-06-12",
      revisions: [{ v: 1, date: "2026-06" }, { v: 2, date: "2026-07" }],
      lede: "你对 Kimi 的印象, 大概还停在「长文本」那一年。它早不是那个工具了 —— 到 K3, 它长成一套对标 OpenAI / Anthropic 的全栈。这本书讲这套栈, 以及该用它的哪一面。",
      posterSummary: "两年时间, 它从「能读长文的框」长成了模型、Agent、API 一整套栈。印象不更新, 你就只用到它的一个角。",
    },
    {
      slug: "02-stack",
      title: "全景 · 一套对标前沿的栈",
      titleShort: "全景",
      titleEn: "",
      readTime: "7 MIN",
      publishedAt: "2026-06-12",
      revisions: [{ v: 1, date: "2026-06" }, { v: 2, date: "2026-07" }],
      lede: "Kimi 现在的产品线几乎是照着 OpenAI 和 Anthropic 摆的: 聊天加会员、多模态模型、Agent 与 Agent Swarm、Deep Research、Kimi Code、API、开源权重。这章给整套栈画张图, 每块对标谁、缺了谁。",
      posterSummary: "把 Kimi 的入口和 ChatGPT、Claude 一一对上号, 你会发现它早是一套完整的栈。这章只画地图: 哪一面对着你哪类活、对标谁。",
    },
    {
      slug: "03-models",
      title: "挑模型 · K3、K2.7-Code 与 K2.6",
      titleShort: "挑模型",
      titleEn: "",
      readTime: "7 MIN",
      publishedAt: "2026-06-12",
      revisions: [{ v: 1, date: "2026-06" }, { v: 2, date: "2026-07" }],
      lede: "K3 是 2.8 万亿参数、1M 上下文的新旗舰, 思考永远开着; K2.7-Code 仍是编码专线, K2.6 退为平价通用。这章讲三颗脑子怎么分工、什么时候值得付 K3 的价、什么时候回 frontier。",
      posterSummary: "默认就是最强的 K3, 思考再也关不掉; 便宜的两颗也各有用处。什么时候值得付 K3 的价, 什么时候回 frontier, 这章算清。",
    },
    {
      slug: "04-modes",
      title: "四模式 · 快答、深想、交办、集群",
      titleShort: "四模式",
      titleEn: "",
      readTime: "6 MIN",
      publishedAt: "2026-06-12",
      revisions: [{ v: 1, date: "2026-06" }, { v: 2, date: "2026-07" }],
      lede: "输入框那几个模式 ——Instant / Thinking / Agent / Agent Swarm—— 是 Kimi 把「问答」和「做事」分开的旋钮。挑错了要么慢、要么不够使。这章给一条线。",
      posterSummary: "同一个输入框, 四档模式干的是四种活。核心判断只有一条: 挑能办成事的最低那一档。",
    },
    {
      slug: "05-agent",
      title: "交办 · Agent 直接做成品",
      titleShort: "交办",
      titleEn: "",
      readTime: "7 MIN",
      publishedAt: "2026-06-12",
      revisions: [{ v: 1, date: "2026-06" }, { v: 2, date: "2026-07" }],
      lede: "Agent 模式不只给答案, 它做出网站、幻灯、文档、表格。这章讲什么时候该把整件活交给它, 什么时候它只是花架子。",
      posterSummary: "Agent 交的不是一段文字, 是排好版的 PPT、算好的表、能上线的网页。从这章开始, 一问一答变成「说清要什么, 直接收成品」。",
    },
    {
      slug: "06-swarm",
      title: "大活 · Agent Swarm 与 Kimi Claw",
      titleShort: "大活",
      titleEn: "",
      readTime: "7 MIN",
      publishedAt: "2026-06-12",
      revisions: [{ v: 1, date: "2026-06" }, { v: 2, date: "2026-07" }],
      lede: "一个 agent 不够, 就放一群。Agent Swarm 能调度上百个子 agent 并行干大活; Kimi Claw 是更新、更险的一条线。这章讲什么活值得动用这么大的阵仗。",
      posterSummary: "一群子 agent 并行换时间, 一个常驻 agent 7×24 替你动手。两条线都猛, 代价也都要先认清。",
    },
    {
      slug: "07-research",
      title: "查证 · Deep Research 出带出处的报告",
      titleShort: "查证",
      titleEn: "",
      readTime: "7 MIN",
      publishedAt: "2026-06-12",
      revisions: [{ v: 1, date: "2026-06" }, { v: 2, date: "2026-07" }],
      lede: "有些问题要的不是一段回答, 是一份每条结论都带出处的报告。Kimi 的 Deep Research 会自己读几百个网页、交叉核对。这章讲什么活值得等这一趟。",
      posterSummary: "它自己读几百个网页、交叉核对, 写成每条结论都带出处的报告。什么活值得等这几分钟, 什么活普通对话三秒就够。",
    },
    {
      slug: "08-code",
      title: "写码 & 接 API · 把 Kimi 配进你的 Agent",
      titleShort: "写码",
      titleEn: "",
      readTime: "12 MIN",
      publishedAt: "2026-06-12",
      revisions: [{ v: 1, date: "2026-06" }, { v: 2, date: "2026-07" }],
      lede: "Kimi Code 是跑在终端、对标 Claude Code 的第一方编码 agent; 开放平台有 OpenAI 与 Anthropic 两套兼容协议, Claude Code、OpenCode、Pi 改几行配置就能接, Codex 要借 CC-Switch 的本地路由。这章给每个 agent 的最小配置, 也说清哪里接不了。",
      posterSummary: "终端里的 Kimi Code、OpenAI / Anthropic 双兼容的 API、一键切换的 CC-Switch —— 国内开发者的顺手三件套, 这章给最小配置。",
    },
    {
      slug: "09-selection",
      title: "选档 & 取舍 · 买哪档, 什么时候回 frontier",
      titleShort: "选档",
      titleEn: "",
      readTime: "6 MIN",
      publishedAt: "2026-06-12",
      revisions: [{ v: 1, date: "2026-06" }, { v: 2, date: "2026-07" }],
      lede: "选档不是看价格, 是看你缺 Agent 次数、Agent 集群, 还是 Kimi Code 额度。这章把五档会员摆开, 说清订阅不含 API, 以及什么活该回 Claude / GPT、什么活交给 DeepSeek。",
      posterSummary: "五档差的是分项额度, 不是模型。买哪一档、哪些活干脆别交给它, 这章一次算清。",
    },
    {
      slug: "10-playbook",
      title: "实战速查 · 哪类活该用哪一面",
      titleShort: "速查",
      titleEn: "",
      readTime: "5 MIN",
      publishedAt: "2026-06-12",
      revisions: [{ v: 1, date: "2026-06" }, { v: 2, date: "2026-07" }],
      isLastChapter: true,
      lede: "前面把每一面单独讲透了, 这一页把判断压成一张表: 常见的活该走哪一面、怎么用、注意什么。对上哪一行, 就用那一面。",
      posterSummary: "全书的判断压成一张表: 对上哪一行, 就走哪一面; 对不上的, 别硬留在 Kimi 这。",
    },
  ],
};
